# Generated by Django 5.0.1 on 2024-01-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.FileField(null=True, upload_to='static/uploads'),
        ),
    ]
